# Generated by Django 4.2.2 on 2023-06-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traininglogentry',
            old_name='date',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='traininglogentry',
            name='date_training',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
