# Generated by Django 4.2.2 on 2023-06-30 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangoApp', '0003_rename_technique_traininglogentry_techniques'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechniqueLibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('related_techniques', models.TextField(blank=True, null=True)),
                ('outside_resources', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Needs Improvement', 'Needs Improvement'), ('Proficient', 'Proficient'), ('Mastered', 'Mastered')], max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
