# Generated by Django 4.2.2 on 2023-06-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0004_techniquelibraryentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniquelibraryentry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='traininglogentry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
