# Generated by Django 4.2.2 on 2023-07-01 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0005_alter_techniquelibraryentry_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techniquelibraryentry',
            old_name='date_added',
            new_name='Date_Added',
        ),
        migrations.RenameField(
            model_name='techniquelibraryentry',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='techniquelibraryentry',
            old_name='outside_resources',
            new_name='Outside_Resources',
        ),
        migrations.RenameField(
            model_name='techniquelibraryentry',
            old_name='related_techniques',
            new_name='Related_Techniques',
        ),
        migrations.RenameField(
            model_name='techniquelibraryentry',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='techniquelibraryentry',
            old_name='technique_name',
            new_name='Technique_Name',
        ),
        migrations.RenameField(
            model_name='traininglogentry',
            old_name='date_added',
            new_name='Date_Added',
        ),
        migrations.RenameField(
            model_name='traininglogentry',
            old_name='notes',
            new_name='Notes',
        ),
        migrations.RenameField(
            model_name='traininglogentry',
            old_name='techniques',
            new_name='Techniques',
        ),
        migrations.RenameField(
            model_name='traininglogentry',
            old_name='date_training',
            new_name='Training_Date',
        ),
    ]
