# Generated by Django 5.0.3 on 2024-03-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0006_rename_date_added_techniquelibraryentry_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglogentry',
            name='Training_Date',
            field=models.DateField(null=True),
        ),
    ]
