# Generated by Django 5.0.3 on 2024-03-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0007_alter_traininglogentry_training_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininglogentry',
            name='Duration',
            field=models.IntegerField(blank=True, help_text='Duration in Minutes', null=True),
        ),
    ]
