# Generated by Django 5.0.3 on 2024-03-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0008_traininglogentry_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniquelibraryentry',
            name='Outside_Resources',
        ),
        migrations.AlterField(
            model_name='traininglogentry',
            name='Duration',
            field=models.IntegerField(blank=True, help_text='Minutes', null=True),
        ),
    ]
