# Generated by Django 5.0.3 on 2024-03-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0009_remove_techniquelibraryentry_outside_resources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniquelibraryentry',
            name='Related_Techniques',
        ),
        migrations.AddField(
            model_name='techniquelibraryentry',
            name='Related_Techniques',
            field=models.ManyToManyField(blank=True, to='djangoApp.techniquelibraryentry'),
        ),
    ]
