# Generated by Django 5.0.3 on 2024-03-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0010_remove_techniquelibraryentry_related_techniques_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniquelibraryentry',
            name='Related_Techniques',
        ),
        migrations.AddField(
            model_name='techniquelibraryentry',
            name='Outside_Resources',
            field=models.TextField(blank=True, null=True),
        ),
    ]
