# Generated by Django 5.0.3 on 2024-03-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0011_remove_techniquelibraryentry_related_techniques_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniquelibraryentry',
            name='Outside_Resources',
        ),
    ]
