# Generated by Django 5.0.3 on 2024-03-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0012_remove_techniquelibraryentry_outside_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniquelibraryentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='technique_library_images/'),
        ),
        migrations.AddField(
            model_name='techniquelibraryentry',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='technique_library_videos/'),
        ),
        migrations.AddField(
            model_name='traininglogentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='training_log_images/'),
        ),
        migrations.AddField(
            model_name='traininglogentry',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='training_log_videos/'),
        ),
    ]
