# Generated by Django 5.0.3 on 2024-04-02 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0013_techniquelibraryentry_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechniqueSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeriesTechniqueLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.techniquelibraryentry')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='djangoApp.techniqueseries')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
