# Generated by Django 5.0.3 on 2024-04-02 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0014_techniqueseries_seriestechniquelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniqueseries',
            name='techniques',
            field=models.ManyToManyField(blank=True, related_name='technique_series', through='djangoApp.SeriesTechniqueLink', to='djangoApp.techniquelibraryentry'),
        ),
        migrations.AlterField(
            model_name='seriestechniquelink',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_techniques', to='djangoApp.techniqueseries'),
        ),
        migrations.AlterField(
            model_name='seriestechniquelink',
            name='technique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technique_links', to='djangoApp.techniquelibraryentry'),
        ),
    ]
