# Generated by Django 5.0.3 on 2024-04-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0015_techniqueseries_techniques_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniqueseries',
            name='techniques',
        ),
        migrations.RemoveField(
            model_name='techniqueseries',
            name='user',
        ),
        migrations.DeleteModel(
            name='SeriesTechniqueLink',
        ),
        migrations.DeleteModel(
            name='TechniqueSeries',
        ),
    ]
