# Generated by Django 5.0.3 on 2024-04-04 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0016_remove_techniqueseries_techniques_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechniqueSeriesEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SeriesName', models.CharField(max_length=200, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechniqueSeriesLinking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TechniqueLibraryEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.techniquelibraryentry')),
                ('TechniqueSeriesEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.techniqueseriesentry')),
            ],
            options={
                'unique_together': {('TechniqueSeriesEntry', 'TechniqueLibraryEntry')},
            },
        ),
        migrations.AddField(
            model_name='techniqueseriesentry',
            name='Techniques',
            field=models.ManyToManyField(blank=True, through='djangoApp.TechniqueSeriesLinking', to='djangoApp.techniquelibraryentry'),
        ),
    ]
