# Generated by Django 5.0.3 on 2024-04-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0017_techniqueseriesentry_techniqueserieslinking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techniqueserieslinking',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='techniqueserieslinking',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
